version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check
      - store_artifacts:
          path: mobile/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: mobile/build/reports
          destination: reports
